### ISSUE TITLE
Time Sync

### ISSUE THREAD

**Issue by Yumshot** [OfficialDarkzy/DRP-Core#3]
Sometimes upon first load to the server after restart time syncing causes a crash.
Believe the issue may becoming from the ConnectionSetTime server event. 
> **Recreate** : At the current time I'm unable to recreate the case repeatedly. Seems like a possibility that somewhere within ConnectionSetTime's event causes the issue. 

Will update with progress at a later date unless you figure this out.

**Comment by OfficialDarkzy** [comment]
Cheers for the report I will investigate

**Comment by OfficialDarkzy** [comment]
I have put a delay on this, i will get a "isPlayerReady" system in place soon for this but for now this should fix it

**Comment by Yumshot** [comment]
Awesome , yeah I'll check it out and let ya know!

**Comment by Yumshot** [comment]
Possibly fixed with your last commits 

> 681bd77 + 1dba50c 

Will close and reopen if the issue is not fixed!

**Comment by Yumshot** [comment]
Issue is still present.
However happens less frequently now?

**Comment by OfficialDarkzy** [comment]
Righto, I will make a system now and push it to master branch

**Comment by Yumshot** [comment]
Have not noticed this issue since Commit 300c1f1
